$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$base = Join-Path $root 'assets\صور للمجالات'
$relBase = 'assets/صور للمجالات'

function Rel([string]$full) {
    return ($full.Substring($root.Length + 1) -replace '\\', '/')
}

function Dim([string]$path) {
    $img = [System.Drawing.Image]::FromFile($path)
    try { return @{ w = $img.Width; h = $img.Height } }
    finally { $img.Dispose() }
}

function ImgObj([string]$path) {
    $d = Dim $path
    return [ordered]@{ src = (Rel $path); w = $d.w; h = $d.h }
}

function IsImage($f) {
    return @('.png', '.jpg', '.jpeg', '.webp', '.gif') -contains $f.Extension.ToLower()
}

function ArtScore([string]$name) {
    $n = [System.IO.Path]::GetFileNameWithoutExtension($name)
    if ($n -eq 'واجهة 1') { return 0 }
    if ($n -eq 'واجهة') { return 1 }
    $m = [regex]::Match($n, '(\d+)')
    if ($m.Success) { return 10 + [int]$m.Groups[1].Value }
    return 9999
}

$catIds = [ordered]@{
    'محاماة'                = 'law'
    'تصاميم إعلانية'        = 'ads'
    'صور مصغرة ريلز'        = 'reels'
    'طبي'                   = 'medical'
    'بيرسونال براندينج'     = 'personal'
    'كاروسيلات'             = 'carousels'
}

$categories = @()

foreach ($name in $catIds.Keys) {
    $dir = Join-Path $base $name
    if (-not (Test-Path -LiteralPath $dir)) { continue }
    $id = $catIds[$name]
    $files = @(Get-ChildItem -LiteralPath $dir -File | Where-Object { IsImage $_ })
    $coverFile = $files | Where-Object { $_.BaseName -eq 'واجهة' } | Select-Object -First 1

    if ($id -eq 'carousels') {
        $subDirs = @(Get-ChildItem -LiteralPath $dir -Directory)
        $projects = @()
        foreach ($sd in $subDirs) {
            $sFiles = @(Get-ChildItem -LiteralPath $sd.FullName -File | Where-Object { IsImage $_ })
            if ($sFiles.Count -eq 0) { continue }
            $sorted = @($sFiles | Sort-Object @{ Expression = { ArtScore $_.Name } }, Name)
            $thumb = $sorted | Where-Object { $_.BaseName -eq 'Artboard 1' } | Select-Object -First 1
            if (-not $thumb) { $thumb = $sorted | Where-Object { $_.BaseName -eq 'واجهة 1' } | Select-Object -First 1 }
            if (-not $thumb) { $thumb = $sorted | Where-Object { $_.BaseName -eq 'واجهة' } | Select-Object -First 1 }
            if (-not $thumb) { $thumb = $sorted[0] }
            $slides = @($sorted | ForEach-Object { ImgObj $_.FullName })
            $projects += [ordered]@{
                title  = $sd.Name
                cover  = (ImgObj $thumb.FullName)
                slides = $slides
            }
        }
        $coverImg = $null
        foreach ($sf in $subDirs) {
            $cand = Get-ChildItem -LiteralPath $sf.FullName -File | Where-Object { $_.BaseName -eq 'واجهة 1' } | Select-Object -First 1
            if ($cand) { $coverImg = ImgObj $cand.FullName; break }
        }
        if (-not $coverImg) { $coverImg = (ImgObj $files[0].FullName) }
        $supports = @()
        foreach ($sf in $subDirs) {
            $cand = Get-ChildItem -LiteralPath $sf.FullName -File | Where-Object { $_.BaseName -eq 'واجهة' } | Select-Object -First 1
            if ($cand) { $supports += (ImgObj $cand.FullName) }
            if ($supports.Count -ge 2) { break }
        }
        $categories += [ordered]@{
            id            = $id
            title         = $name
            type          = 'carousel'
            cover         = $coverImg
            supportLeft   = $(if ($supports.Count -ge 1) { $supports[0] } else { $coverImg })
            supportRight  = $(if ($supports.Count -ge 2) { $supports[1] } else { $coverImg })
            projects      = $projects
        }
    }
    else {
        $cover = $null
        if ($coverFile) { $cover = ImgObj $coverFile.FullName } else { $cover = ImgObj $files[0].FullName }
        $works = @()
        foreach ($f in ($files | Sort-Object Name)) {
            if ($coverFile -and $f.FullName -eq $coverFile.FullName) { continue }
            $works += (ImgObj $f.FullName)
        }
        $categories += [ordered]@{
            id    = $id
            title = $name
            type  = 'normal'
            cover = $cover
            works = $works
        }
    }
}

$payload = [ordered]@{ categories = $categories }
$json = $payload | ConvertTo-Json -Depth 12

$out = Join-Path $root 'assets\js\portfolio-data.js'
$content = "/* Auto-generated by tools/gen-portfolio.ps1 - do not edit by hand. */`nwindow.RAQEEM_PORTFOLIO = $json;`n"
[System.IO.File]::WriteAllText($out, $content, (New-Object System.Text.UTF8Encoding($false)))
Write-Output ("Wrote " + $out + " (" + (Get-Item -LiteralPath $out).Length + " bytes)")
