/* ==========================================================================
   Generates lightweight web-delivery WebP variants for the portfolio and the
   homepage hero. Original artwork is only ever READ — never modified.

   Output:
     assets/opt/<hash>/{t400,t800,full}.webp
     assets/opt/site/hero-*.webp
     assets/js/portfolio-opt.js   (manifest consumed by assets/js/main.js)

   Run from the project root after adding/replacing artwork:
     npm install sharp
     node tools/optimize-images.mjs
   ========================================================================== */

import sharp from 'sharp';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'assets', 'opt');
const SITE = path.join(OUT, 'site');
const FULL_MAX_W = 1280;

const hash = (s) => crypto.createHash('md5').update(s).digest('hex').slice(0, 10);
const rel = (p) => path.relative(ROOT, p).replace(/\\/g, '/');
const ensureDir = (p) => fs.mkdirSync(p, { recursive: true });

const dataSrc = fs.readFileSync(path.join(ROOT, 'assets/js/portfolio-data.js'), 'utf8');
global.window = {};
eval(dataSrc);
const cats = window.RAQEEM_PORTFOLIO.categories;

const sources = new Set();
const add = (o) => { if (o && o.src) sources.add(o.src); };
for (const c of cats) {
  add(c.cover);
  if (c.type === 'carousel') (c.projects || []).forEach((p) => { add(p.cover); p.slides.forEach(add); });
  else (c.works || []).forEach(add);
}

const manifest = {};
let bytesIn = 0;
let bytesOut = 0;

for (const src of sources) {
  const abs = path.join(ROOT, src);
  const meta = await sharp(abs).metadata();
  const dir = path.join(OUT, hash(src));
  ensureDir(dir);
  const fullPath = path.join(dir, 'full.webp');
  const t400Path = path.join(dir, 't400.webp');
  const t800Path = path.join(dir, 't800.webp');
  await sharp(abs).resize({ width: Math.min(meta.width, FULL_MAX_W), withoutEnlargement: true })
    .webp({ quality: 90, effort: 5, chromaSubsampling: '4:4:4' }).toFile(fullPath);
  await sharp(abs).resize({ width: 400, withoutEnlargement: true })
    .webp({ quality: 80, effort: 5, chromaSubsampling: '4:4:4' }).toFile(t400Path);
  await sharp(abs).resize({ width: 800, withoutEnlargement: true })
    .webp({ quality: 80, effort: 5, chromaSubsampling: '4:4:4' }).toFile(t800Path);
  const f = await sharp(fullPath).metadata();
  manifest[src] = { t400: rel(t400Path), t800: rel(t800Path), full: rel(fullPath), w: meta.width, h: meta.height, fw: f.width, fh: f.height };
  bytesIn += fs.statSync(abs).size;
  bytesOut += fs.statSync(fullPath).size + fs.statSync(t400Path).size + fs.statSync(t800Path).size;
}

ensureDir(SITE);
const heroSrc = path.join(ROOT, 'assets/images/Home Page.png');
const heroMeta = await sharp(heroSrc).metadata();
const heroWidths = [900, 1400, heroMeta.width];
const heroOut = {};
for (const w of heroWidths) {
  const p = path.join(SITE, 'hero-' + w + '.webp');
  await sharp(heroSrc).resize({ width: w, withoutEnlargement: true })
    .webp({ quality: 86, effort: 5, chromaSubsampling: '4:4:4' }).toFile(p);
  heroOut[w] = rel(p);
}

const payload = {
  generated: new Date().toISOString(),
  site: { hero: { srcset: heroWidths.map((w) => heroOut[w] + ' ' + w + 'w').join(', '), w: heroMeta.width, h: heroMeta.height } },
  images: manifest,
};

fs.writeFileSync(
  path.join(ROOT, 'assets/js/portfolio-opt.js'),
  '/* Auto-generated by tools/optimize-images.mjs - do not edit by hand. */\nwindow.RAQEEM_OPT = ' + JSON.stringify(payload) + ';\n'
);

console.log('generated', sources.size, 'image sets');
console.log('originals total', (bytesIn / 1048576).toFixed(1), 'MB');
console.log('optimized total', (bytesOut / 1048576).toFixed(1), 'MB');
console.log('ratio', ((bytesOut / bytesIn) * 100).toFixed(1) + '%');
